services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - mongo
      # - postgres
    env_file:
      - .env
    networks:
      - payload1
  # Ensure your DATABASE_URL uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    image: mongo:latest
    container_name: payload-mongo
    ports:
      - '27018:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo_data:/data/db
    networks:
      - payload1
    # logging:
    #   driver: none

  # Uncomment the following to use postgres
  # postgres:
  #   restart: always
  #   image: postgres:latest
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: payload_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - payload1

  influxdb :
    image: influxdb:2.7-alpine
    container_name: payload_influx
    ports: 
    - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=livestream-org
      - DOCKER_INFLUXDB_INIT_BUCKET=stream-metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=cricket9846
    volumes :
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2

    networks:
    - payload1

    restart: unless-stopped 

  # # Optional: Grafana for visualization
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: livestream-grafana
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #     - GF_INSTALL_PLUGINS=influxdata-influxdb-datasource
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   networks:
  #     - livestream-network
  #   depends_on:
  #     - influxdb
  #   restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
  # pgdata:
  node_modules:
  influxdb-data:
  influxdb-config:
  # grafana-data:

networks:
  payload1:
    driver: bridge
